import Link from "next/link";
import { ConnectorStatusBadge, LastHeartbeat, SourceSummary } from "@/components/connector-presenters";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import type { ManagedConnector } from "@/lib/types";

export function ConnectorTable({ connectors, detailBase, platform = false, canRetire = false, onRetire }: { connectors: ManagedConnector[]; detailBase: string; platform?: boolean; canRetire?: boolean; onRetire?: (connector: ManagedConnector) => void }) {
  if (!connectors.length) return <Card className="p-8 text-center text-sm text-slate-500">No connectors have been registered.</Card>;
  const headers = platform ? ["Connector Name", "Tenant", "Version", "Environment", "Instance ID", "Connector ID", "Status", "Last Heartbeat", "Sources", "Actions"] : ["Name", "Version", "Environment", "Status", "Last heartbeat", "Source summary", "Registered at", "Actions"];
  return <Card className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b bg-slate-50"><tr>{headers.map(value => <th className="whitespace-nowrap px-4 py-3 font-medium text-slate-500" key={value}>{value}</th>)}</tr></thead><tbody>{connectors.map(connector => <tr className="border-b align-top last:border-0" key={connector.id}><td className="px-4 py-4 font-medium"><Link className="text-blue-600 hover:underline" href={`${detailBase}/${connector.id}`}>{connector.name}</Link></td>{platform && <td className="px-4 py-4">{connector.tenant_name ?? "Unknown tenant"}</td>}<td className="px-4 py-4">{connector.version}</td><td className="px-4 py-4">{connector.environment}</td>{platform && <><td className="px-4 py-4 font-mono text-xs">{connector.instance_id}</td><td className="px-4 py-4 font-mono text-xs">{connector.id}</td></>}<td className="px-4 py-4"><ConnectorStatusBadge status={connector.status}/></td><td className="whitespace-nowrap px-4 py-4"><LastHeartbeat value={connector.last_heartbeat_at}/></td><td className="whitespace-nowrap px-4 py-4"><SourceSummary total={connector.source_total} healthy={connector.source_healthy} unhealthy={connector.source_unhealthy} disabled={connector.source_disabled}/></td>{!platform && <td className="whitespace-nowrap px-4 py-4">{new Date(connector.registered_at).toLocaleString()}</td>}<td className="px-4 py-4"><div className="flex gap-2"><Button asChild variant="outline"><Link href={`${detailBase}/${connector.id}`}>Details</Link></Button>{platform && connector.tenant_slug && <Button asChild variant="ghost"><a href={`/t/${connector.tenant_slug}`} target="_blank" rel="noreferrer">Open tenant portal</a></Button>}{canRetire && !connector.retired_at && <Button variant="danger" onClick={() => onRetire?.(connector)}>Retire</Button>}</div></td></tr>)}</tbody></table></Card>;
}
