"""Add tenant SSO config table

Revision ID: 411ad47e1acb
Revises: bf9ddb1a05e4
Create Date: 2026-07-08 16:09:38.455001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '411ad47e1acb'
down_revision: Union[str, Sequence[str], None] = 'bf9ddb1a05e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_sso_configs',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.Enum('ENTRA_ID', 'OKTA', 'GENERIC_OIDC', name='sso_provider'), nullable=False),
    sa.Column('issuer_url', sa.String(length=500), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('client_secret_encrypted', sa.String(length=1000), nullable=False),
    sa.Column('authorization_endpoint', sa.String(length=500), nullable=False),
    sa.Column('token_endpoint', sa.String(length=500), nullable=False),
    sa.Column('jwks_uri', sa.String(length=500), nullable=False),
    sa.Column('redirect_uri', sa.String(length=500), nullable=False),
    sa.Column('scopes', sa.String(length=500), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', name='uq_tenant_sso_config_tenant_id')
    )
    op.create_index(op.f('ix_tenant_sso_configs_tenant_id'), 'tenant_sso_configs', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenant_sso_configs_tenant_id'), table_name='tenant_sso_configs')
    op.drop_table('tenant_sso_configs')
    # ### end Alembic commands ###
