"""Add tenant OIDC auth sessions

Revision ID: 49fcf1214f3e
Revises: 65c6cf461aab
Create Date: 2026-07-10 23:03:42.152201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49fcf1214f3e'
down_revision: Union[str, Sequence[str], None] = '65c6cf461aab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_oidc_auth_sessions',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('state_hash', sa.String(length=64), nullable=False),
    sa.Column('nonce', sa.String(length=255), nullable=False),
    sa.Column('code_verifier', sa.String(length=255), nullable=True),
    sa.Column('redirect_uri', sa.String(length=500), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_oidc_auth_sessions_expires_at'), 'tenant_oidc_auth_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_tenant_oidc_auth_sessions_state_hash'), 'tenant_oidc_auth_sessions', ['state_hash'], unique=True)
    op.create_index(op.f('ix_tenant_oidc_auth_sessions_tenant_id'), 'tenant_oidc_auth_sessions', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenant_oidc_auth_sessions_tenant_id'), table_name='tenant_oidc_auth_sessions')
    op.drop_index(op.f('ix_tenant_oidc_auth_sessions_state_hash'), table_name='tenant_oidc_auth_sessions')
    op.drop_index(op.f('ix_tenant_oidc_auth_sessions_expires_at'), table_name='tenant_oidc_auth_sessions')
    op.drop_table('tenant_oidc_auth_sessions')
    # ### end Alembic commands ###
