"""Add tenant admin invites table

Revision ID: 65c6cf461aab
Revises: 7f53b1aeba4f
Create Date: 2026-07-09 00:29:32.350285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65c6cf461aab'
down_revision: Union[str, Sequence[str], None] = '7f53b1aeba4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_admin_invites',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_platform_admin_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_platform_admin_id'], ['platform_admin_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_tenant_admin_invites_created_by_platform_admin_id'), 'tenant_admin_invites', ['created_by_platform_admin_id'], unique=False)
    op.create_index(op.f('ix_tenant_admin_invites_email'), 'tenant_admin_invites', ['email'], unique=False)
    op.create_index(op.f('ix_tenant_admin_invites_tenant_id'), 'tenant_admin_invites', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenant_admin_invites_tenant_id'), table_name='tenant_admin_invites')
    op.drop_index(op.f('ix_tenant_admin_invites_email'), table_name='tenant_admin_invites')
    op.drop_index(op.f('ix_tenant_admin_invites_created_by_platform_admin_id'), table_name='tenant_admin_invites')
    op.drop_table('tenant_admin_invites')
    # ### end Alembic commands ###
