"""Allow disabled tenant SSO config

Revision ID: 7f53b1aeba4f
Revises: e37ee2d2a1b6
Create Date: 2026-07-09 00:24:38.232871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f53b1aeba4f'
down_revision: Union[str, Sequence[str], None] = 'e37ee2d2a1b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenant_sso_configs', 'issuer_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('tenant_sso_configs', 'client_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('tenant_sso_configs', 'client_secret_encrypted',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
    op.alter_column('tenant_sso_configs', 'authorization_endpoint',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('tenant_sso_configs', 'token_endpoint',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('tenant_sso_configs', 'jwks_uri',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('tenant_sso_configs', 'redirect_uri',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenant_sso_configs', 'redirect_uri',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('tenant_sso_configs', 'jwks_uri',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('tenant_sso_configs', 'token_endpoint',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('tenant_sso_configs', 'authorization_endpoint',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('tenant_sso_configs', 'client_secret_encrypted',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
    op.alter_column('tenant_sso_configs', 'client_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('tenant_sso_configs', 'issuer_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    # ### end Alembic commands ###
