"""Add tenant users table

Revision ID: b4063697a55b
Revises: 411ad47e1acb
Create Date: 2026-07-08 23:36:12.652334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4063697a55b'
down_revision: Union[str, Sequence[str], None] = '411ad47e1acb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_users',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('auth_source', sa.Enum('LOCAL', 'SSO', name='tenant_user_auth_source'), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('external_subject', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_users_email'), 'tenant_users', ['email'], unique=False)
    op.create_index(op.f('ix_tenant_users_external_subject'), 'tenant_users', ['external_subject'], unique=False)
    op.create_index(op.f('ix_tenant_users_tenant_id'), 'tenant_users', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_tenant_users_username'), 'tenant_users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenant_users_username'), table_name='tenant_users')
    op.drop_index(op.f('ix_tenant_users_tenant_id'), table_name='tenant_users')
    op.drop_index(op.f('ix_tenant_users_external_subject'), table_name='tenant_users')
    op.drop_index(op.f('ix_tenant_users_email'), table_name='tenant_users')
    op.drop_table('tenant_users')
    # ### end Alembic commands ###
