"""Add platform admin login tracking fields

Revision ID: bf9ddb1a05e4
Revises: f8b3f31f1cb5
Create Date: 2026-07-06 00:18:12.409865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf9ddb1a05e4'
down_revision: Union[str, Sequence[str], None] = 'f8b3f31f1cb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "platform_admin_users",
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "platform_admin_users",
        sa.Column("failed_login_attempts", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column(
        "platform_admin_users",
        sa.Column("locked", sa.Boolean(), server_default=sa.false(), nullable=False),
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('platform_admin_users', 'locked')
    op.drop_column('platform_admin_users', 'failed_login_attempts')
    op.drop_column('platform_admin_users', 'last_login_at')
    # ### end Alembic commands ###
