"""Add tenant URL

Revision ID: e37ee2d2a1b6
Revises: b4063697a55b
Create Date: 2026-07-08 23:52:27.935738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e37ee2d2a1b6'
down_revision: Union[str, Sequence[str], None] = 'b4063697a55b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('tenant_url', sa.String(length=500), nullable=True))
    op.create_index(op.f('ix_tenants_tenant_url'), 'tenants', ['tenant_url'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenants_tenant_url'), table_name='tenants')
    op.drop_column('tenants', 'tenant_url')
    # ### end Alembic commands ###
